In [112]:
import pandas as pd
import numpy as np
import glob
import os

In [113]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None) 
pd.set_option('display.max_colwidth', None)

In [114]:
csv_dir = "data/"
csv_files = glob.glob(os.path.join(csv_dir, "*.csv"))

In [115]:
dfs = [pd.read_csv(f) for f in csv_files]
df = pd.concat(dfs, ignore_index=True)

In [116]:
df['soa_ms'] = df['soa_ms'].round()

In [117]:
np.sort(df['soa_ms'].unique())

array([14., 21., 28., 35., 42., 49., 56., 62., 69.])

In [118]:
for soa in np.sort(df['soa_ms'].unique()):
    print("SOA:", soa, "\tDetections:", df[(df['soa_ms'] == soa) & (df['prime_shown']) & (~df['catch_trial'])]['detect_yn'].sum())

SOA: 14.0 	Detections: 3
SOA: 21.0 	Detections: 1
SOA: 28.0 	Detections: 4
SOA: 35.0 	Detections: 7
SOA: 42.0 	Detections: 5
SOA: 49.0 	Detections: 6
SOA: 56.0 	Detections: 4
SOA: 62.0 	Detections: 4
SOA: 69.0 	Detections: 9


In [126]:
df['detect_yn'].sum() / len(df)

0.26666666666666666

In [149]:
df[~df['detect_yn']]['confidence'].mean()

59.696969696969695

In [125]:
len(df)

180

In [ ]:
df['prime_correct'].sum() / len(df)

0.5444444444444444

In [137]:
len(df[df['prime_correct'] & df['prime_congruent']])

64

In [147]:
df_clean = df.dropna()
len(df_clean[~df_clean['prime_correct'] & ~df_clean['prime_congruent']])

47

In [148]:
64+47/180

64.2611111111111

In [120]:
df[df['catch_trial']]

subj  trial  soa_ms  catch_trial  detect_yn  confidence  rt_prime_ms  \
27   Sevan     27    28.0         True      False          60     515.7548   
30   Sevan     30    49.0         True      False          60     852.3750   
33   Sevan     33    28.0         True      False          60     307.1283   
42   Sevan     42    21.0         True      False          60     154.2455   
43   Sevan     43    21.0         True      False          80     427.1234   
45   Sevan     45    62.0         True      False          70     382.7424   
82   Sevan     82    49.0         True      False          50     418.7226   
105  Sevan    105    42.0         True      False          40     282.8508   
115  Sevan    115    14.0         True      False          60     438.2186   
127  Sevan    127    56.0         True      False          50     247.5205   
130  Sevan    130    35.0         True      False          70     378.6246   
140  Sevan    140    56.0         True      False          90     254.9786   
146  Sevan    146    35.0         True      False          80     285.8066   
153  Sevan    153    14.0         True      False          70     173.9877   
164  Sevan    164    69.0         True      False          70     139.6189   
165  Sevan    165    69.0         True      False          70     381.3041   
166  Sevan    166    42.0         True      False          60     169.5582   
167  Sevan    167    62.0         True       True          40     539.0030   

     prime_shown  prime_congruent prime_correct  threshold  
27          True            False         False  41.639379  
30          True            False          True  41.639379  
33          True            False          True  41.639379  
42          True            False          True  41.639379  
43          True            False          True  41.639379  
45          True            False         False  41.639379  
82          True            False          True  41.639379  
105         True            False          True  41.639379  
115         True            False         False  41.639379  
127         True            False          True  41.639379  
130         True            False         False  41.639379  
140         True            False         False  41.639379  
146         True            False          True  41.639379  
153         True            False          True  41.639379  
164         True            False         False  41.639379  
165         True            False          True  41.639379  
166         True            False          True  41.639379  
167         True            False          True  41.639379

In [ ]:
df[df]

In [122]:
df[df['prime_congruent']]['rt_prime_ms'].mean()

439.1547530992991

In [123]:
df[~df['prime_congruent']]['rt_prime_ms'].mean()

392.64038787928945

In [70]:
df[(df['soa_ms'] == 155) & (df['catch_trial']==True)]

subj  trial  soa_ms  catch_trial  detect_yn  confidence  rt_prime_ms  \
0    Sevan      0   155.0         True      False          20     998.9581   
6    Sevan      6   155.0         True      False          40     681.7258   
16   Sevan     16   155.0         True      False          50    1051.9180   
27   Sevan     27   155.0         True      False          90   10645.6353   
29   Sevan     29   155.0         True      False          40     721.5351   
50   Sevan     50   155.0         True      False          60     424.9135   
51   Sevan     51   155.0         True       True          50    1154.3335   
55   Sevan     55   155.0         True      False          80    1476.3202   
76   Sevan     76   155.0         True       True          30     408.5268   
91   Sevan     91   155.0         True      False          70     482.7999   
103  Sevan    103   155.0         True      False          80     536.2017   
105  Sevan    105   155.0         True      False          80     474.0216   
108  Sevan    108   155.0         True      False          80     244.7286   
112  Sevan    112   155.0         True      False         100     480.2410   
114  Sevan    114   155.0         True      False         100     464.8708   
125  Sevan    125   155.0         True      False          40     479.0689   
130  Sevan    130   155.0         True      False          30     415.4175   
163  Sevan    163   155.0         True      False          60     697.0791   
167  Sevan    167   155.0         True      False          60     879.1196   
174  Sevan    174   155.0         True      False          60     422.3231   

     prime_shown  prime_congruent prime_correct   threshold  
0           True            False         False  154.632468  
6           True            False         False  154.632468  
16          True            False         False  154.632468  
27          True            False         False  154.632468  
29          True            False          True  154.632468  
50          True            False          True  154.632468  
51          True            False          True  154.632468  
55          True            False          True  154.632468  
76          True            False         False  154.632468  
91          True            False          True  154.632468  
103         True            False         False  154.632468  
105         True            False          True  154.632468  
108         True            False         False  154.632468  
112         True            False         False  154.632468  
114         True            False         False  154.632468  
125         True            False          True  154.632468  
130         True            False         False  154.632468  
163         True            False         False  154.632468  
167         True            False         False  154.632468  
174         True            False         False  154.632468

In [78]:
df[~df['prime_shown']]

subj  trial  soa_ms  catch_trial  detect_yn  confidence  rt_prime_ms  \
11   Sevan     11   155.0        False       True          90     384.6153   
20   Sevan     20   155.0        False       True          70     331.9550   
28   Sevan     28   155.0        False      False          40   26065.4760   
39   Sevan     39   155.0        False       True          60    3060.0457   
46   Sevan     46   155.0        False       True          50     752.2775   
52   Sevan     52   155.0        False       True         100     399.6792   
61   Sevan     61   155.0        False       True         100     425.6216   
69   Sevan     69   155.0        False       True          60     341.8765   
80   Sevan     80   155.0        False      False          40     385.9284   
107  Sevan    107   155.0        False      False          80     292.0796   
118  Sevan    118   155.0        False       True          50     222.1128   
121  Sevan    121   155.0        False       True          70     472.6821   
128  Sevan    128   155.0        False      False          60     851.4196   
131  Sevan    131   155.0        False       True         100     371.1576   
136  Sevan    136   155.0        False       True          70     358.1001   
140  Sevan    140   155.0        False      False           0   83022.5252   
143  Sevan    143   155.0        False      False          30     477.2910   
155  Sevan    155   155.0        False       True          60     308.2363   
159  Sevan    159   155.0        False       True         100     428.2839   
168  Sevan    168   155.0        False       True          70     389.1008   

     prime_shown  prime_congruent prime_correct   threshold  
11         False            False           NaN  154.632468  
20         False            False           NaN  154.632468  
28         False            False           NaN  154.632468  
39         False            False           NaN  154.632468  
46         False            False           NaN  154.632468  
52         False            False           NaN  154.632468  
61         False            False           NaN  154.632468  
69         False            False           NaN  154.632468  
80         False            False           NaN  154.632468  
107        False            False           NaN  154.632468  
118        False            False           NaN  154.632468  
121        False            False           NaN  154.632468  
128        False            False           NaN  154.632468  
131        False            False           NaN  154.632468  
136        False            False           NaN  154.632468  
140        False            False           NaN  154.632468  
143        False            False           NaN  154.632468  
155        False            False           NaN  154.632468  
159        False            False           NaN  154.632468  
168        False            False           NaN  154.632468

In [80]:
max(1, int(round(10**0.84)))*7

49

In [63]:
df[df['soa_ms'] == 205]['detect_yn'].sum()

9

In [47]:
df[df['prime_congruent'] & ~df['detect_yn'] & (df['rt_prime_ms']<1000)]['rt_prime_ms'].mean()

565.1493363759735

In [48]:
df[~df['prime_congruent'] & ~df['detect_yn'] & (df['rt_prime_ms']<1000)]['rt_prime_ms'].mean()

538.9123675916848

In [99]:
FRAME_MS = 6.943

In [110]:
scale = np.array([0.25, 0.45, 0.65, 0.85, 1.0, 1.15, 1.35, 1.60, 2.0])
thresh = 9 * FRAME_MS

In [111]:
np.round(np.clip(np.round(thresh * scale), 1, None).astype(int) / FRAME_MS)

array([ 2.,  4.,  6.,  8.,  9., 10., 12., 14., 18.])

In [90]:
np.round(scale * thresh)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10.])